version: "3"
services:
  redis:
    image: redis
    ports:
      - "6380:6379"
  postgres:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gitinsights
  front-end:
    image: gitinsights:v001
    command: yarn dev:client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pull: 1
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/gitinsights
  api:
    image: gitinsights:v001
    command: yarn dev:api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pull: 1
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/gitinsights
    depends_on:
      - postgres
      - redis